---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-apm-ogas-kr-v1-instrumentation
  failurePolicy: Fail
  name: minstrumentation.kb.io
  rules:
  - apiGroups:
    - apm.ogas.kr
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instrumentations
  sideEffects: None
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-apm-ogas-kr-v1-instrumentation
  failurePolicy: Fail
  name: vinstrumentation.kb.io
  rules:
  - apiGroups:
    - apm.ogas.kr
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    resources:
    - instrumentations
  sideEffects: None
