# permissions for end users to edit instrumentations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: instrumentation-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: apm-instrumentation-operator
    app.kubernetes.io/part-of: apm-instrumentation-operator
    app.kubernetes.io/managed-by: kustomize
  name: instrumentation-editor-role
rules:
- apiGroups:
  - apm.ogas.kr
  resources:
  - instrumentations
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apm.ogas.kr
  resources:
  - instrumentations/status
  verbs:
  - get
